-- Migration script to populate root_cause table with previous hardcoded values
-- Run this in psql: psql -h localhost -d defects -U postgres -f migrate_root_causes.sql

INSERT INTO root_cause (root_cause) VALUES
('Scratch Back camera'),
('Damage White RF Coaxial Main PCBA'),
('Damage Ultra Camera'),
('Damage Motor'),
('PCBA Damage'),
('Damage Sub PCBA'),
('Damage Speaker'),
('Scratch Ultra Lens'),
('Black RF Defect Material'),
('DECO Plate Defect Material'),
('Damage Receiver'),
('ANT PCBA Damage'),
('Sub PCBA Defect Material'),
('Receiver Defect Material'),
('OIS Camera Defect Material'),
('Ultra Camera Defect Material'),
('Fingerprint Defect Material'),
('NG BTB Assembly'),
('Lens Defect Material'),
('Battery Cover Defect Material'),
('Battery Defect Material'),
('OLEDM Defect Material'),
('Damage BTB'),
('Dust in Light Sensor'),
('NG Optical Rubber Assy'),
('Damage Camera BTB'),
('Damage Fingerprint BTB'),
('Dent Rear Camera'),
('Dust in Fingerprint'),
('Dust Rear Camera'),
('Dust Front Camera'),
('Dust BTB'),
('Glue on Light Sensor'),
('Broken Sidekey Antennas'),
('sim card damage'),
('Glue on Sidekey'),
('No Black RF Cable'),
('No White RF Cable'),
('Locked Cameras'),
('Wipped QR Code'),
('Mix Material'),
('Mix Cameras'),
('Broken Sub PCBA Antenna'),
('Broken Main PCBA Antenna'),
('Missing Files'),
('Damage Speaker Rubber'),
('NG Rework Material'),
('Wide Screw Hole'),
('Missing Screw'),
('Up Screw'),
('Up Black RF'),
('Up Speaker'),
('Open Middle frame Clips Asc'),
('CCD Machine Error'),
('Screw Machine High Torque'),
('Missing Bracket'),
('Missing Speaker'),
('Sub PCBA Component Damage'),
('Dust BTB connector'),
('FPC BTB Damage'),
('Dust Speaker'),
('Motor Defect Material'),
('Pending Repair'),
('Battery BTB Broken Damage'),
('PCBA Component Damage'),
('Cut Camera Ultra'),
('Cut FPC'),
('Cut OLEDM FPC'),
('Scratch Back Camera Lens Asc'),
('Dust PCBA'),
('NG Assembly BTB'),
('Missing Sticker'),
('Dust Sude Key'),
('Dust Recever'),
('NG Assembly Finger Print'),
('White RF Cut'),
('Software Upgrade'),
('Waterproof foam cover middle frame connect pins'),
('Cat Rear Ultra'),
('NG Assimbly Missing Sticker'),
('Rubber Cut Damage'),
('FPC Damage'),
('Side Asc'),
('NG Assembly Motor'),
('Shifted FPC'),
('NG Assembly'),
('NG Assembly Missing'),
('Power On'),
('Dust Middle frame'),
('Dust Ultra Camera'),
('Dust Sub PCBA'),
('ANT PCBA Defect Material'),
('OIS Camera Damage'),
('Speaker Defect Material'),
('Cut Side Key'),
('NG Assembly Double Face'),
('Damage Foam'),
('NG Foam Assembly'),
('Dust PCBA'),
('Shifted Sidekey'),
('PCBA Defect Material'),
('OLEDM Damage'),
('Damage Middle frame'),
('Front Camera Defect Material'),
('Black RF Cut'),
('Reversed Receiver'),
('Damage BTB OLEDM'),
(' Middle frame Defect Material'),
('Double Face Receiver issue'),
('Shifted motor'),
('Mic Rubber material defect'),
('speaker Rubber material defect'),
('Shifted Receiver'),
('Shifted Conductive'),
('NG Assembly Rceeiver Rubber'),
('Auto Restart'),
('Audio Jack'),
('Damage PCBA BTB'),
('Damaged Flash'),
('audio jac'),
('Dent Middle Frame'),
('DENT TP'),
('NG Reveiver FPC'),
('Flash Defect Material'),
('Damage Main Mic Rubber'),
('Missing Flash'),
('FPC Defect Material'),
('OLEDM BTB Damage'),
('Damage PCBA Component'),
('Repair Issue'),
('Camera Ultra Defect Material'),
('Fake Issue'),
('Shifted FPC Receiver'),
('Bad Ring Assembly'),
('Main Camera BTB Damage'),
('Front Camera BTB Damage'),
('Shifted Bracket Pad'),
('Shifted Flash PCBA'),
('Upper Bracket Defect Material'),
('Damage Upper Bracket'),
('OLEDM Defect Material'),
('Finger Under lens In Front'),
('Machince Issue'),
('UV Machine Issue'),
('Screen Machine Issue'),
('Corrosion in Battery Cover'),
('Damage Black RF Coaxial Main PCBA'),
('Damage Coaxial Sub PCBA'),
('Extra Material in OLEDM'),
('Wrong Camera CAP removal method lead to FPC bended'),
('Device by incident dropped while handling by PD operator'),
('Device by incident hit while handling to the M/C'),
('Device Bad handling on the Assy line by PD operator'),
('Device Bad handling on the Test line by PD Asc'),
('Device Bad handling on the Packing line by PD operator'),
('point deco'),
('Pending'),
('Batrrey Cover damage'),
('Antenna Bracket Defect Material'),
('NG ASSY Rubber'),
('Damage OLEDM'),
('Up White RF'),
('White RF Defect Material'),
('Damage Steel Sheet'),
('Steel sheet scratch')
ON CONFLICT (root_cause) DO NOTHING;

